# Exercise

We are going to download CSV data from NOAA's website that gathers tornado data for both Texas and Oklahoma. We will then clean the data, select only the fields we are interested in, and load it into a SQLite database.

**STEP 1:** First import the necessary libraries.

In [21]:
import pandas as pd
import sqlite3

**STEP 2:** Import data from CSV

In [22]:
df = pd.read_csv("storm_data.csv")
df

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE,STATE
0,1299990,OSAGE CO.,WYNONA,01/08/2026,841,Tornado,NaN,EF1,0,0,...,WYNONA,01/08/2026,842,36.5380,-96.3270,36.5470,-96.3180,"A tornado damaged the roofs of several homes, ...",A strong upper level disturbance and associate...,OKLAHOMA
1,1309165,LIBERTY CO.,KEVIN,02/03/2026,1524,Tornado,NaN,EF0,0,0,...,KEVIN,02/03/2026,1525,30.2531,-95.1021,30.2541,-95.0980,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ...",TEXAS
2,1309177,LIBERTY CO.,KEVIN,02/03/2026,1527,Tornado,NaN,EF0,0,0,...,PLUM GROVE,02/03/2026,1533,30.2547,-95.0866,30.2575,-95.0584,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ...",TEXAS
3,1311609,MCCLAIN CO.,PURCELL,01/08/2026,724,Tornado,NaN,EF2,0,0,...,PURCELL,01/08/2026,731,34.9670,-97.4430,35.0250,-97.3540,This tornado developed near 180th Street and L...,A fast-moving quasi-linear convective system (...,OKLAHOMA
4,1311610,CLEVELAND CO.,LEXINGTON,01/08/2026,731,Tornado,NaN,EF0,0,0,...,LEXINGTON,01/08/2026,734,35.0250,-97.3540,35.0470,-97.3110,This is a continuation of the Purcell tornado ...,A fast-moving quasi-linear convective system (...,OKLAHOMA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,1339920,PUSHMATAHA CO.,ANTLERS,05/27/2026,1407,Tornado,NaN,EF1,0,0,...,ANTLERS,05/27/2026,1408,34.2306,-95.6147,34.2414,-95.6171,"This tornado damaged the hospital, damaged a f...",Thunderstorms increased across eastern Oklahom...,OKLAHOMA
107,1339922,CHOCTAW CO.,GOODLAND,05/27/2026,1745,Tornado,NaN,EFU,0,0,...,GOODLAND,05/27/2026,1745,33.9935,-95.5518,33.9935,-95.5518,This brief tornado was observed by several peo...,Thunderstorms increased across eastern Oklahom...,OKLAHOMA
108,1340662,GUADALUPE CO.,NEW BERLIN,05/26/2026,920,Tornado,NaN,EF1,0,0,...,NEW BERLIN,05/26/2026,925,29.5052,-98.0991,29.5029,-98.0508,The National Weather Service conducted a damag...,An upper shortwave trough moved across Texas a...,TEXAS
109,1340663,MAVERICK CO.,QUEMADO,05/26/2026,1619,Tornado,NaN,EF0,0,0,...,QUEMADO,05/26/2026,1622,29.0314,-100.6361,29.0243,-100.6335,The National Weather Service received reports ...,An upper shortwave trough moved across Texas a...,TEXAS
110,1341339,IRION CO.,BARNHART,05/19/2026,1519,Tornado,NaN,EFU,0,0,...,BARNHART,05/19/2026,1521,31.3000,-101.1500,31.3031,-101.1462,There was a brief tornado touchdown reported.,A few severe thunderstorms produced large hail...,TEXAS

**STEP 3:** Extract out only the fields of interest.

In [23]:
fields = ["CZ_NAME_STR","BEGIN_LOCATION","BEGIN_DATE","BEGIN_TIME","TOR_F_SCALE",
          "DEATHS_DIRECT","INJURIES_DIRECT","DAMAGE_PROPERTY_NUM","DAMAGE_CROPS_NUM",
          "STATE_ABBR","END_LOCATION","END_DATE","END_TIME",
          "EVENT_NARRATIVE","EPISODE_NARRATIVE"]

df.drop(columns=[col for col in df if col not in fields], inplace=True)

df

,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,END_LOCATION,END_DATE,END_TIME,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,OSAGE CO.,WYNONA,01/08/2026,841,EF1,0,0,200000,0,WYNONA,01/08/2026,842,"A tornado damaged the roofs of several homes, ...",A strong upper level disturbance and associate...
1,LIBERTY CO.,KEVIN,02/03/2026,1524,EF0,0,0,6000,0,KEVIN,02/03/2026,1525,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
2,LIBERTY CO.,KEVIN,02/03/2026,1527,EF0,0,0,23000,0,PLUM GROVE,02/03/2026,1533,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
3,MCCLAIN CO.,PURCELL,01/08/2026,724,EF2,0,0,400000,0,PURCELL,01/08/2026,731,This tornado developed near 180th Street and L...,A fast-moving quasi-linear convective system (...
4,CLEVELAND CO.,LEXINGTON,01/08/2026,731,EF0,0,0,10000,0,LEXINGTON,01/08/2026,734,This is a continuation of the Purcell tornado ...,A fast-moving quasi-linear convective system (...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,PUSHMATAHA CO.,ANTLERS,05/27/2026,1407,EF1,0,0,50000,0,ANTLERS,05/27/2026,1408,"This tornado damaged the hospital, damaged a f...",Thunderstorms increased across eastern Oklahom...
107,CHOCTAW CO.,GOODLAND,05/27/2026,1745,EFU,0,0,0,0,GOODLAND,05/27/2026,1745,This brief tornado was observed by several peo...,Thunderstorms increased across eastern Oklahom...
108,GUADALUPE CO.,NEW BERLIN,05/26/2026,920,EF1,0,0,0,0,NEW BERLIN,05/26/2026,925,The National Weather Service conducted a damag...,An upper shortwave trough moved across Texas a...
109,MAVERICK CO.,QUEMADO,05/26/2026,1619,EF0,0,0,0,0,QUEMADO,05/26/2026,1622,The National Weather Service received reports ...,An upper shortwave trough moved across Texas a...
110,IRION CO.,BARNHART,05/19/2026,1519,EFU,0,0,0,0,BARNHART,05/19/2026,1521,There was a brief tornado touchdown reported.,A few severe thunderstorms produced large hail...

**STEP 4:** Convert date/time fields to a single datetime in new fields. Clean up the times so they have 4 digits and a colon. Then Convert those new fields to UTC. Finally, drop the original date/time fields.

In [24]:
def clean_time(time):
    time_str = str(time).strip()
    c = f"{'0' * (4-len(time_str))}{time_str}"
    return c[0:2] + ":" + c[2:4]

df.insert(2, 'BEGIN_DATETIME', pd.to_datetime(df['BEGIN_DATE'] + ' ' + df['BEGIN_TIME'].apply(clean_time))  \
    .dt.tz_localize('US/Central') \
    .dt.tz_convert('UTC')
          )

df.insert(3, 'END_DATETIME', pd.to_datetime(df['END_DATE'] + ' ' + df['END_TIME'].apply(clean_time))  \
    .dt.tz_localize('US/Central') \
    .dt.tz_convert('UTC')
)

df.drop(["BEGIN_DATE", "BEGIN_TIME", "END_DATE", "END_TIME"], axis=1, inplace=True)

df

,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATETIME,END_DATETIME,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,END_LOCATION,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,OSAGE CO.,WYNONA,2026-01-08 14:41:00+00:00,2026-01-08 14:42:00+00:00,EF1,0,0,200000,0,WYNONA,"A tornado damaged the roofs of several homes, ...",A strong upper level disturbance and associate...
1,LIBERTY CO.,KEVIN,2026-02-03 21:24:00+00:00,2026-02-03 21:25:00+00:00,EF0,0,0,6000,0,KEVIN,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
2,LIBERTY CO.,KEVIN,2026-02-03 21:27:00+00:00,2026-02-03 21:33:00+00:00,EF0,0,0,23000,0,PLUM GROVE,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
3,MCCLAIN CO.,PURCELL,2026-01-08 13:24:00+00:00,2026-01-08 13:31:00+00:00,EF2,0,0,400000,0,PURCELL,This tornado developed near 180th Street and L...,A fast-moving quasi-linear convective system (...
4,CLEVELAND CO.,LEXINGTON,2026-01-08 13:31:00+00:00,2026-01-08 13:34:00+00:00,EF0,0,0,10000,0,LEXINGTON,This is a continuation of the Purcell tornado ...,A fast-moving quasi-linear convective system (...
...,...,...,...,...,...,...,...,...,...,...,...,...
106,PUSHMATAHA CO.,ANTLERS,2026-05-27 19:07:00+00:00,2026-05-27 19:08:00+00:00,EF1,0,0,50000,0,ANTLERS,"This tornado damaged the hospital, damaged a f...",Thunderstorms increased across eastern Oklahom...
107,CHOCTAW CO.,GOODLAND,2026-05-27 22:45:00+00:00,2026-05-27 22:45:00+00:00,EFU,0,0,0,0,GOODLAND,This brief tornado was observed by several peo...,Thunderstorms increased across eastern Oklahom...
108,GUADALUPE CO.,NEW BERLIN,2026-05-26 14:20:00+00:00,2026-05-26 14:25:00+00:00,EF1,0,0,0,0,NEW BERLIN,The National Weather Service conducted a damag...,An upper shortwave trough moved across Texas a...
109,MAVERICK CO.,QUEMADO,2026-05-26 21:19:00+00:00,2026-05-26 21:22:00+00:00,EF0,0,0,0,0,QUEMADO,The National Weather Service received reports ...,An upper shortwave trough moved across Texas a...
110,IRION CO.,BARNHART,2026-05-19 20:19:00+00:00,2026-05-19 20:21:00+00:00,EFU,0,0,0,0,BARNHART,There was a brief tornado touchdown reported.,A few severe thunderstorms produced large hail...

**STEP 5:** Rename a fiew fields to make them easier to identify for end users.

In [25]:
df.rename(columns= { 
    "CZ_NAME_STR": "COUNTY_NAME",
    "DAMAGE_PROPERTY_NUM" :"DAMAGE_PROPERTY_USD", 
    "DAMAGE_CROPS_NUM" :"DAMAGE_CROPS_USD"
})

,COUNTY_NAME,BEGIN_LOCATION,BEGIN_DATETIME,END_DATETIME,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_USD,DAMAGE_CROPS_USD,END_LOCATION,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,OSAGE CO.,WYNONA,2026-01-08 14:41:00+00:00,2026-01-08 14:42:00+00:00,EF1,0,0,200000,0,WYNONA,"A tornado damaged the roofs of several homes, ...",A strong upper level disturbance and associate...
1,LIBERTY CO.,KEVIN,2026-02-03 21:24:00+00:00,2026-02-03 21:25:00+00:00,EF0,0,0,6000,0,KEVIN,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
2,LIBERTY CO.,KEVIN,2026-02-03 21:27:00+00:00,2026-02-03 21:33:00+00:00,EF0,0,0,23000,0,PLUM GROVE,Storms moved through Liberty county on Februar...,"On the third of February, a tornado formed in ..."
3,MCCLAIN CO.,PURCELL,2026-01-08 13:24:00+00:00,2026-01-08 13:31:00+00:00,EF2,0,0,400000,0,PURCELL,This tornado developed near 180th Street and L...,A fast-moving quasi-linear convective system (...
4,CLEVELAND CO.,LEXINGTON,2026-01-08 13:31:00+00:00,2026-01-08 13:34:00+00:00,EF0,0,0,10000,0,LEXINGTON,This is a continuation of the Purcell tornado ...,A fast-moving quasi-linear convective system (...
...,...,...,...,...,...,...,...,...,...,...,...,...
106,PUSHMATAHA CO.,ANTLERS,2026-05-27 19:07:00+00:00,2026-05-27 19:08:00+00:00,EF1,0,0,50000,0,ANTLERS,"This tornado damaged the hospital, damaged a f...",Thunderstorms increased across eastern Oklahom...
107,CHOCTAW CO.,GOODLAND,2026-05-27 22:45:00+00:00,2026-05-27 22:45:00+00:00,EFU,0,0,0,0,GOODLAND,This brief tornado was observed by several peo...,Thunderstorms increased across eastern Oklahom...
108,GUADALUPE CO.,NEW BERLIN,2026-05-26 14:20:00+00:00,2026-05-26 14:25:00+00:00,EF1,0,0,0,0,NEW BERLIN,The National Weather Service conducted a damag...,An upper shortwave trough moved across Texas a...
109,MAVERICK CO.,QUEMADO,2026-05-26 21:19:00+00:00,2026-05-26 21:22:00+00:00,EF0,0,0,0,0,QUEMADO,The National Weather Service received reports ...,An upper shortwave trough moved across Texas a...
110,IRION CO.,BARNHART,2026-05-19 20:19:00+00:00,2026-05-19 20:21:00+00:00,EFU,0,0,0,0,BARNHART,There was a brief tornado touchdown reported.,A few severe thunderstorms produced large hail...

**STEP 6:** Load the data into a SQLite database file, into a table called `TORNADO_TRACK`.

In [26]:
conn = sqlite3.connect('my_database.db')
df.to_sql("TORNADO_TRACK", conn, if_exists='replace', index=False)

# 4. VERIFY DATA IS LOADED USING A SELECT query 
sql_df = pd.read_sql("SELECT * FROM TORNADO_TRACK", conn)
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
  display(sql_df)

conn.close()

,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATETIME,END_DATETIME,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,END_LOCATION,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,OSAGE CO.,WYNONA,2026-01-08 14:41:00+00:00,2026-01-08 14:42:00+00:00,EF1,0,0,200000,0,WYNONA,"A tornado damaged the roofs of several homes, destroyed a large outbuilding, snapped power poles, and blew down trees. Based on this damage, maximum estimated wind in the tornado was 90 to 100 mph.","A strong upper level disturbance and associated cold front translated into the Southern Plains on the 8th. An unseasonably warm and moist air mass had spread into eastern Oklahoma ahead of this system, which resulted in weak instability across the area. A line of thunderstorms developed into eastern Oklahoma from the west during the morning hours of the 8th. Strong wind fields and wind shear associated with the approaching upper level system, combined with the weak instability, supported an environment in which the stronger thunderstorms within the squall line were able to develop low level circulations. One such circulation resulted in a brief, weak tornado and wind gusts to 88 mph in Osage County."
1,LIBERTY CO.,KEVIN,2026-02-03 21:24:00+00:00,2026-02-03 21:25:00+00:00,EF0,0,0,6000,0,KEVIN,"Storms moved through Liberty county on February 3rd, where a tornado warned storm passed through the Plum Grove area. Initially broadcast media reported trees down near intersection of County Road 3709 and County Road 3732. In the aftermath of this storm, a survey team was dispatched to assess the damage across the area.||The survey team found that this storm produced two tornadoes, this being the first. According to the survey team, the tornado appeared to initially touched down within a wooded area between CR 3708 and CR 3709, then turned eastward along CR 3709 for a short distance before lifting up shortly before River Ln. A drone was used to assess an areal view of the damage, though the survey team noted that they did not see any damage in the deeply wooded area along the East Fork of the San Jacinto River. Therefore, the survey team concluded that the first tornado ended just before the River Ln and CR 3709 intersection. The majority of the damage seen was broken trunks and branches of pine trees and fences down. Power lines were also reported blown down, but the power line poles remained upright. This tornado was rated as an EF0 with a maximum estimated wind speed of 80 mph. This maximum wind speed was based on Softwood Trees (TS) with a DOD of 2. Survey teams noted that the trees in question had reported beetle damage.","On the third of February, a tornado formed in Plum Grove area in Liberty county."
2,LIBERTY CO.,KEVIN,2026-02-03 21:27:00+00:00,2026-02-03 21:33:00+00:00,EF0,0,0,23000,0,PLUM GROVE,"Storms moved through Liberty county on February 3rd, where a tornado warned storm passed through the Plum Grove area. Initially broadcast media reported trees down near intersection of County Road 3709 and County Road 3732. In the aftermath of this storm, a survey team was dispatched to assess the damage across the area.||The survey team found that this storm produced two tornadoes, this being the second. This second tornado started along FM 1010 and Wooden Ln, indicated by an uprooted tree and broken wood signage. The tornado entered a largely empty field between FM 1010 and CR 3405, but still saw some tree damage. The tornado then entered the Bella Vista subdivision, causing tree damage, fence damage, and metal structure damage between CR 3405 and CR 3404. No further damage was seen beyond the intersection of CR 3404 and CR 3410. This tornado was rated as an EF0. The most significant damage occurred at a metal structure off of FM 1010 with estimated peak winds of 85 mph. This assessment is based on a metal building system (MBS) with a DOD of 3.","On the third of February, a tornado formed in Plum Grove area in Liberty county."
3,MCCLAIN CO.,PURCELL,2026-01-08 13:24:00+00:00,2026-01-08 13:31:00+00:00,EF2,0,0,400000,0,PURCELL,"This tornado developed near 180th Street and Ladd Road southwest of Purcell and moved northeast. One home about 3 miles southwest of Purcell had the roof removed. A semi on Interstate 35 just west of Purcell was pushed over injuring one person. The tornado then moved through Purcell causing roof damage to a few homes and damaging utility poles and trees. Moving out of the northeast side of Purcell, the tornado crossed the Canadian River into Cleveland County.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
4,CLEVELAND CO.,LEXINGTON,2026-01-08 13:31:00+00:00,2026-01-08 13:34:00+00:00,EF0,0,0,10000,0,LEXINGTON,"This is a continuation of the Purcell tornado that moved into Cleveland County from McClain County. After crossing the Canadian River into Cleveland County, the tornado damaged and outbuilding near Moffatt Road. Otherwise, damage to tree branches was noted along U.S. Highway 77 north of Lexington, and northeast of 84th Street and York Road where the tornado likely dissipated.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
5,CLEVELAND CO.,LAKE THUNDERBIRD DAM,2026-01-08 13:44:00+00:00,2026-01-08 13:45:00+00:00,EF0,0,0,5000,0,LAKE THUNDERBIRD DAM,"This tornado likely developed over the northern arm of Lake Thunderbird, then moved northeast damaging trees after moving onshore. A few branches were snapped off of trees just northeast of 156th Avenue NE and Tecumseh Road.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
6,CLEVELAND CO.,STELLA,2026-01-08 13:52:00+00:00,2026-01-08 13:53:00+00:00,EF0,0,0,20000,0,STELLA,"This tornado developed near SE 149th Street just west of the Pottawatomie County line. In Cleveland County, a garage and RV were damaged as well as a couple of trees and a flagpole. The tornado moved northeast crossing Pottawatomie Road into Pottawatomie County.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
7,POTTAWATOMIE CO.,PINK,2026-01-08 13:53:00+00:00,2026-01-08 13:57:00+00:00,EF1,0,0,75000,0,DALE,"This is a continuation of a tornado that developed in Cleveland County. After crossing Pottawatomie Road into Pottawatomie County, a number of large, dead trees were broken, a small outbuilding destroyed and a porch was damaged. Continuing northeast, an outbuilding was damaged along Fishmarket Road, and at least two homes received roof damage in the area between the Shawnee Twin Lakes. The tornado dissipated northeast of Homer Lane Road and Patterson Road between the lakes.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
8,POTTAWATOMIE CO.,SHAWNEE,2026-01-08 14:06:00+00:00,2026-01-08 14:09:00+00:00,EF1,0,0,100000,0,AYDELOTTE,"A tornado developed on the north side of Shawnee, just north of Shawnee Regional Airport. The tornado damaged one home moving through a neighborhood west of State Highway 3E, but damage was mostly to trees and fences. Crossing Interstate 40, a hotel received roof damage just east of Shawnee Mall, and a bread truck was blown over near a Wal Mart. Two businesses were damaged northeast of the hotel and just west of Harrison Avenue. At one business, a roof AC unit was damaged, garage doors were blown in, vehicle windows were broken, and trees and power lines were downed. The tornado dissipated near Harrison Avenue south of Garretts Lake Road.","A fast-moving quasi-linear convective system (QLCS) swept across portions of central, southern and eastern Oklahoma on the morning of the 8th. This convective system was tied to the passage of a compact upper wave across the region, resulting in very strong wind fields within a weakly unstable boundary layer. In addition to sporadic pockets of thunderstorm wind damage, and generally sub-severe hail, a few tornadoes occurred in a corridor from near Purcell, OK to Shawnee, OK."
9,SHELBY CO.,JAMES,2026-02-15 00:03:00+00:00,2026-02-15 00:05:00+00:00,EF1,0,0,25000,0,JAMES,"This brief EF-1 tornado with estimated maximum winds near 95 mph began along County Road 3156, where a few trees were downed, and then it traveled southeast to cross Highway 7 where it intersected with County Road 3153. Most of the damage here was also to trees with a consolidated area of snapped softwood trees giving the tornado its estimated maximum windspeed rating. The tornado then continued to the southeast and was judged to have ended just after crossing County Road 3215. One outbuilding was destroyed at this location, but otherwise the survey team could verify only minor damage done to a few buildings here and earlier when the tornado crossed Highway 7. Localized snapping of tree trunks was also quite evident around a pond just to the west of County Road 3215.","An upper level trough ejected east-northeast from the Desert Southwest into Northwest Texas and Western Oklahoma during the afternoon and evening of February 14th, which resulted in the increase of very warm, humid air north across the region from the Gulf. In advance of this system, southwest flow aloft became established, with increasing instability at the surface and aloft coupled with strong wind shear and an approaching cold front enhancing large scale ascent across much of the Four State Region. As a result, showers and thunderstorms, some of which became severe over portions of East Texas and Central Louisiana, developed and spread east across the area during the late afternoon through the evening. Multiple reports of wind damage were received, with a brief, weak isolated tornado having been spawned in Northeast Shelby County near the James community."
10,KINNEY CO.,STANDART,2026-03-10 21:40:00+00:00,2026-03-10 21:40:00+00:00,EFU,0,0,0,0,STANDART,"A brief tornado occurred over open country north of US-90 as observed and photographed by storm spotters along US-90. The tornado appears to have remained over open country with no damage reported. With no apparent damage, we could not determine a path length or width.","An upper-level trough moved across northern Mexico and into West Texas, generating thunderstorms along and ahead of a dryline within a region of steep lapse rates and high instability. Isolated thunderstorms began forming east of the dryline around 1500CDT, including a long-tracked supercell which produced a brief tornado, strong winds, and a swath of large to very large hail from the Del Rio area to the Hill Country. A line of thunderstorms formed along the dryline over Val Verde County after 1900CDT which tracked across the southern Edwards Plateau and Hill Country through the evening, producing some strong winds before weakening near the I-35 corridor."
11,CREEK CO.,BRISTOW JONES ARPT,2026-03-06 23:18:00+00:00,2026-03-06 23:32:00+00:00,EF1,0,0,150000,0,BELLVUE,"The tornado developed approximately four miles northwest of Bristow, west of South 401st West Avenue and north of West 221st Street South. Moving northeast, it crossed South 401st West Avenue, where it destroyed a single-wide mobile home and an outbuilding. As the tornado continued northeast across Highway 16, it uprooted trees and snapped large limbs. At the intersection of Highway 48 and West 181st Street South, the tornado impacted an industrial site, collapsing overhead doors and removing roof sections from two metal buildings. The tornado maintained a northeast track, breaking additional large tree limbs along South 337th West Avenue, before dissipating north of Highway 66. Based on this damage, maximum estimated wind in the tornado was 100 to 110 mph.","Severe thunderstorms developed into eastern Oklahoma during the late afternoon of the 6th, ahead of a surface dry line, and moved across the area through the evening hours. The atmosphere had become strongly unstable across eastern Oklahoma during the afternoon east of the dry line. This instability, combined with very strong low-level and deep-layer wind shear across the region, resulted in the evolution of several long-lived supercell thunderstorms. These supercells produced eleven tornadoes, a couple of which were strong and damaging, large hail up to quarter size, damaging wind gusts, and localized flash flooding."
12,OSAGE CO.,TULSA,2026-03-07 00:24:00+00:00,2026-03-07 00:27:00+00:00,EF1,0,0,200000,0,TULSA,"This is the first segment of a two-segment tornado. This tornado developed near N Gilcrease Museum Road, north of W Newton Street. It moved northeast damaging a number of homes, damaging the roof of an apartment complex, uprooting trees, and snapping numerous large tree limbs in neighborhoods west of N Tisdale Parkway. It then crossed into Tulsa County near W Apache Street. Based on this damage, maximum estimated wind in this segment of the tornado was 90 to 100 mph. This tornado produced a tornadic debris signature from the KINX WSR-88D.","Severe thunderstorms developed into eastern Oklahoma during the late afternoon of the 6th, ahead of a surface dry line, and moved across the area through the evening hours. The atmosphere had become strongly unstable across eastern Oklahoma during the afternoon east of the dry line. This instability, combined with very strong low-level and deep-layer wind shear across the region, resulted in the evolution of several long-lived supercell thunderstorms. These supercells produced eleven tornadoes, a couple of which were strong and damaging, large hail up to quarter size, damaging wind gusts, and localized flash flooding."
13,TULSA CO.,TUL DOWNTOWN ARPK,2026-03-07 00:27:00+00:00,2026-03-07 00:34:00+00:00,EF1,0,0,7000000,0,TURLEY,"This is the second segment of a two-segment tornado. The tornado crossed into Tulsa County near W Apache Street. The tornado damaged many homes and snapped numerous large tree limbs between the county line and the Gilcrease Expressway. It continued to move northeast damaging many homes north of the Gilcrease Expressway, and intensified as it approached E 36th Street N. An office building was severely damaged and the Tulsa Technology Center was severely damaged as the tornado approached N Peoria Avenue. Numerous trees were snapped and uprooted in that area. The tornado moved north-northeast across E 46th Street N and dissipated north of E 61st Street N. Many homes were damaged, a few trees were uprooted, numerous large tree limbs were snapped, and mobile homes were damaged in that portion of the path. Based on this damage, maximum estimated wind in this segment of the tornado was 100 to 110 mph. This tornado produced a tornadic debris signature from the KINX WSR-88D.","Severe thunderstorms developed into eastern Oklahoma during the late afternoon of the 6th, ahead of a surface dry line, and moved across the area through the evening hours. The atmosphere had become strongly unstable across eastern Oklahoma during the afternoon east of the dry line. This instability, combined with very strong low-level and deep-layer wind shear across the region, resulted in the evolution of several long-lived supercell thunderstorms. These supercells produced eleven tornadoes, a couple of which were strong and damaging, large hail up to quarter size, damaging wind gusts, and localized flash flooding."
14,OKFUSKEE CO.,MASON,2026-03-07 00:38:00+00:00,2026-03-07 00:45:00+00:00,EF0,0,0,10000,0,MASON,"Storm chaser video and a debris signature from KINX WSR-88D indicated this tornado began west of Highway 48, about 6 miles north-northwest of Castle. The tornado crossed Highway 48, where it damaged the roof of two mobile homes and snapped tree limbs along the E980 Road before dissipating. Based on this damage, maximum estimated wind in the tornado was 70 to 75 mph.","Severe thunderstorms developed into eastern Oklahoma during the late afternoon of the 6th, ahead of a surface dry line, and moved across the area through the evening hours. The atmosphere had become strongly unstable across eastern Oklahoma during the afternoon east of the dry line. This instability, combined with very strong low-level and deep-layer wind shear across the region, resulted in the evolution of several long-lived supercell thunderstorms. These supercells produced eleven tornadoes, a couple of which were strong and damaging, large hail up to quarter size, damaging wind gusts, and localized flash flooding."
15,TULSA CO.,TURLEY,2026-03-07 00:38:00+00:00,2026-03-07 00:41:00+00:00,EF1,0,0,150000,0,OWASSO,"This tornado developed just west of N Yale Avenue and north of E 76th Street N. It uprooted a tree as it crossed N Yale Avenue and moved northeast across a neighborhood on E 82nd Street N. Several homes were damaged, light poles were blown down, and large tree limbs were snapped. The tornado blew down power poles and snapped large tree limbs as it crossed E 86th Street N. Outbuildings were damaged and large tree limbs were snapped by the tornado as it crossed N Hudson Avenue, and then crossed N Sheridan Avenue, where it dissipated. Based on this damage, maximum estimated wind in the tornado was 90 to 100 mph.","Severe thunderstorms developed into eastern Oklahoma during the late afternoon of the 6th, ahead of a surface dry line, and moved across the area through the evening hours. The atmosphere had become strongly unstable across eastern Oklahoma during the afternoon east of the dry line. This instability, combined with very strong low-level and deep-layer wind shear across the region, resulted in the evolution of several long-lived supercell thunderstorms. These supercells produced eleven tornadoes, a couple of which were strong and damaging, large hail up to quarter size, damaging wind gusts, and localized flash flooding."